### ISSUE TITLE
Upgrading maestro

### ISSUE THREAD

**Issue by iBicha** [georgejecook/maestro-roku#266]
Was looking at https://github.com/georgejecook/maestro-roku/blob/master/docs/About:-Getting-started.md
Which had 
```
    "dependencies": {
        "bslib": "npm:@rokucommunity/bslib@^0.1.1",
        "log": "npm:roku-log@^0.4.1",
        "maestro": "npm:maestro-roku@^0.10.0"
    },
```
I realized 0.10.0 is older, so I tried upgrading, but I have an error (I don't know if this is an ropm thing or maestro thing)

My dependencies look like this

```
  "dependencies": {
    "bslib": "npm:@rokucommunity/bslib@^0.1.1",
    "log": "npm:roku-log@^0.8.0",
    "maestro": "npm:maestro-roku@^0.47.0",
    "roku-requests": "^0.2.0"
  },
```
And this works. If I update  "maestro": "npm:maestro-roku@^0.48.0",
I get
```
brahim@Brahims-MBP my-app % npm i
npm ERR! code 1
npm ERR! path /Users/brahim/Roku/my-app/node_modules/maestro
npm ERR! command failed
npm ERR! command sh -c -- npx ropm copy
npm ERR! npm WARN config production Use `--omit=dev` instead.
npm ERR! npm ERR! code ELSPROBLEMS
npm ERR! npm ERR! missing: bslib@npm:@rokucommunity/bslib@^0.1.1, required by maestro-roku@0.48.6
npm ERR! npm ERR! missing: bslib@npm:@rokucommunity/bslib@^0.1.1, required by log@npm:roku-log@0.4.2
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/brahim/.npm/_logs/2022-10-30T17_26_28_551Z-debug-0.log
npm ERR! Error: Failed to compute prod dependencies: Command failed: npm ls --parseable --prod --depth=Infinity
npm ERR! npm WARN config production Use `--omit=dev` instead.
npm ERR! npm ERR! code ELSPROBLEMS
npm ERR! npm ERR! missing: bslib@npm:@rokucommunity/bslib@^0.1.1, required by maestro-roku@0.48.6
npm ERR! npm ERR! missing: bslib@npm:@rokucommunity/bslib@^0.1.1, required by log@npm:roku-log@0.4.2
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/brahim/.npm/_logs/2022-10-30T17_26_28_551Z-debug-0.log
npm ERR! 
npm ERR!     at InstallCommand.getProdDependencies (/Users/brahim/Roku/my-app/node_modules/ropm/dist/commands/InstallCommand.js:117:23)
npm ERR!     at InstallCommand.processModules (/Users/brahim/Roku/my-app/node_modules/ropm/dist/commands/InstallCommand.js:82:34)
npm ERR!     at InstallCommand.run (/Users/brahim/Roku/my-app/node_modules/ropm/dist/commands/InstallCommand.js:41:20)
npm ERR!     at async CopyCommand.run (/Users/brahim/Roku/my-app/node_modules/ropm/dist/commands/CopyCommand.js:11:9)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brahim/.npm/_logs/2022-10-30T17_26_26_003Z-debug-0.log
```

Strange because bslib@^0.1.1 is right there (besides, its a dependency of maestro anyway)

Thoughts?

**Comment by iBicha** [comment]
Repro steps
- Create empty folder, and init package.json
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```
- Install maestro `ropm install maestro@npm:maestro-roku`
```
brahim@Brahims-MBP Test % ropm install maestro@npm:maestro-roku
running
npm ERR! code 1
npm ERR! path /Users/brahim/Desktop/Test/node_modules/maestro
npm ERR! command failed
npm ERR! command sh -c -- npx ropm copy
npm ERR! npm WARN exec The following package was not found and will be installed: ropm@0.10.10
npm ERR! npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! npm WARN config production Use `--omit=dev` instead.
npm ERR! npm ERR! code ELSPROBLEMS
npm ERR! npm ERR! missing: bslib@npm:@rokucommunity/bslib@^0.1.1, required by maestro-roku@0.53.0
npm ERR! npm ERR! missing: log@npm:roku-log@^0.4.1, required by maestro-roku@0.53.0
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/brahim/.npm/_logs/2022-11-02T16_33_44_888Z-debug-0.log
npm ERR! Error: Failed to compute prod dependencies: Command failed: npm ls --parseable --prod --depth=Infinity
npm ERR! npm WARN config production Use `--omit=dev` instead.
npm ERR! npm ERR! code ELSPROBLEMS
npm ERR! npm ERR! missing: bslib@npm:@rokucommunity/bslib@^0.1.1, required by maestro-roku@0.53.0
npm ERR! npm ERR! missing: log@npm:roku-log@^0.4.1, required by maestro-roku@0.53.0
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/brahim/.npm/_logs/2022-11-02T16_33_44_888Z-debug-0.log
npm ERR! 
npm ERR!     at InstallCommand.getProdDependencies (/Users/brahim/.npm/_npx/dc2dc9ec8dafb315/node_modules/ropm/dist/commands/InstallCommand.js:117:23)
npm ERR!     at InstallCommand.processModules (/Users/brahim/.npm/_npx/dc2dc9ec8dafb315/node_modules/ropm/dist/commands/InstallCommand.js:82:34)
npm ERR!     at InstallCommand.run (/Users/brahim/.npm/_npx/dc2dc9ec8dafb315/node_modules/ropm/dist/commands/InstallCommand.js:41:20)
npm ERR!     at async CopyCommand.run (/Users/brahim/.npm/_npx/dc2dc9ec8dafb315/node_modules/ropm/dist/commands/CopyCommand.js:11:9)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brahim/.npm/_logs/2022-11-02T16_33_34_011Z-debug-0.log
npm WARN config production Use `--omit=dev` instead.
```

On the other hand, installing an older version
- `ropm install maestro@npm:maestro-roku@0.47.0` works fine
